name: Deploy Static HTML to GitHub Pages

on:
  push:
    branches:
      - main  # Setiap kali push ke main, workflow jalan

permissions:
  contents: write  # Diperlukan agar bisa push ke gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .  # Kalau HTML-nya di root folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
